# Generated by Django 6.0.2 on 2026-09-21
#
# Stops a deleted calendar, template or event from silently NULLing the rows
# that depend on it. Existing NULLs are left alone: the column stays
# nullable so rows orphaned by the old SET_NULL behaviour still load and can
# be repaired.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0034_alter_event_id_alter_eventtemplate_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="template",
            field=models.ForeignKey(
                help_text="Select a template for how scheduled Events will look in the calendar.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scheduler.eventtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="eventinstance",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scheduler.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventtemplate",
            name="calendar",
            field=models.ForeignKey(
                help_text="Select the calendar to sync events to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scheduler.schedulingcalendar",
            ),
        ),
    ]
