# Generated by Django 6.0.2 on 2026-09-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_profile_complete",
            field=models.BooleanField(default=True, verbose_name="Profil komplett"),
        ),
    ]
